name: Build images
on:
  push:
  workflow_dispatch:
  schedule:
    - cron: '0 5 1,15 * *' # Run every Day 1 and 15 at midnight

env:
  KERNEL_BRANCH: 6.12.1

jobs:
  build-image:
    runs-on: ubuntu-24.04-arm
    steps:
      - name: Check out build configurations
        uses: actions/checkout@v4

      - name: Substitute placeholders in configs
        run: |
          find . -type f -name "*.cfg" -exec sed -i "s|HOME|$(echo $HOME)|;s|NPROC|$(nproc)|" {} +

      - name: Set up pmbootstrap
        run: |
          git clone https://gitlab.postmarketos.org/postmarketOS/pmbootstrap.git
          mkdir -p ~/.local/bin
          ln -s "$PWD/pmbootstrap/pmbootstrap.py" ~/.local/bin/pmbootstrap
          pmbootstrap --version

      - name: Set up pmaports
        run: |
          echo -e '\n\n' | pmbootstrap init || true
          cd ~/.local/var/pmbootstrap/cache_git/pmaports
          git clone --depth=1 https://github.com/jnz113/pmaports.git /tmp/pmaports
          cp -r /tmp/pmaports/device/testing/*lmi* ./device/testing/
          #git remote add mainlining https://github.com/jnz113/pmaports.git
          #git fetch mainlining nikroks/alioth
          #git reset --hard mainlining/nikroks/alioth

      - name: Clone kernel sources
        run: |
          git clone https://github.com/jnz113/linux.git --single-branch --branch nikroks/alioth --depth 1 ./linux

      - name: Choose lmi device in pmbootstrap to build kernel
        run: |
          cp xiaomi-lmi.cfg ~/.config/pmbootstrap_v3.cfg

      - name: Create artifact directory and Compile
        run: |
          cd linux
          shopt -s expand_aliases
          source ../pmbootstrap/helpers/envkernel.sh
          make defconfig sm8250.config
          mkdir -p /home/runner/out/
          make -j$(nproc) > >(tee -a /home/runner/out/stdout.txt) 2> >(tee -a /home/runner/out/stderr.txt >&2)
          pmbootstrap build --envkernel linux-postmarketos-qcom-sm8250-lmi > >(tee -a /home/runner/out/stdout.txt) 2> >(tee -a /home/runner/out/stderr.txt >&2)
      
      - name: Build xiaomi-lmi
        run: |
          pmbootstrap checksum device-xiaomi-lmi > >(tee -a /home/runner/out/stdout.txt) 2> >(tee -a /home/runner/out/stderr.txt >&2)
          pmbootstrap install --password 147147 > >(tee -a /home/runner/out/stdout.txt) 2> >(tee -a /home/runner/out/stderr.txt >&2)
          pmbootstrap export
          cp /tmp/postmarketOS-export/boot.img /home/runner/out/boot-xiaomi-lmi.img
          cp /tmp/postmarketOS-export/xiaomi-lmi.img /home/runner/out/rootfs-xiaomi-lmi.img
      
      - name: Move log to Out folder
        if: always()
        run: | 
          cp /home/runner/.local/var/pmbootstrap/log.txt /home/runner/out/pmbootstrap-log.txt
      
      - name: Upload logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: output-logs-${{ job.status }}
          path: /home/runner/out/*.txt
          retention-days: 14

          
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: xiaomi-lmi
          path: /home/runner/out/*-lmi.img*
          retention-days: 14
