name: Build images
on:
  push:
  workflow_dispatch:
  schedule:
    - cron: '0 5 1,15 * *' # Run every Day 1 and 15 at midnight

env:
  KERNEL_BRANCH: 6.12.1

jobs:
  build-image:
    runs-on: ubuntu-24.04-arm
    steps:
      - name: Check out build configurations
        uses: actions/checkout@v4

      - name: Substitute placeholders in configs
        run: |
          find . -type f -name "*.cfg" -exec sed -i "s|HOME|$(echo $HOME)|;s|NPROC|$(nproc)|" {} +

      - name: Clone pmbootstrap sources
        run: |
          git clone https://gitlab.postmarketos.org/postmarketOS/pmbootstrap.git
          # cd pmbootstrap
          # git reset --hard f62981d9484fb00cc6669082a26a9b474964972a
      
      - name: Set up pmbootstrap
        run: |
          mkdir -p ~/.local/bin
          ln -s "$PWD/pmbootstrap/pmbootstrap.py" ~/.local/bin/pmbootstrap
          pmbootstrap --version

      - name: Set up pmaports
        run: |
          echo -e '\n\n' | pmbootstrap init || true
          cd ~/.local/var/pmbootstrap/cache_git/pmaports
          git remote add mainlining https://github.com/jnz113/pmaports.git
          git fetch mainlining nikroks/alioth
          git reset --hard mainlining/nikroks/alioth

      - name: Clone kernel sources
        run: |
          git clone https://github.com/jnz113/linux.git --single-branch --branch nikroks/alioth --depth 1 ./linux

      - name: Choose lmi device in pmbootstrap to build kernel
        run: |
          cp xiaomi-lmi.cfg ~/.config/pmbootstrap_v3.cfg

      - name: Create artifact directory and Compile kernel with envkernel
        run: |
          mkdir out
          cd linux
          shopt -s expand_aliases
          source ../pmbootstrap/helpers/envkernel.sh
          make defconfig sm8250.config
          make -j$(nproc)
          pmbootstrap build --envkernel linux-postmarketos-qcom-sm8250-lmi > out/build-stdout-log.txt 2>&1 
        continue-on-error: true

      - name: Move log to Out folder on failure 
        if: failure() 
        run: | 
          mkdir -p out
          cp /home/runner/.local/var/pmbootstrap/log.txt out/

      - name: Build xiaomi-lmi
        run: |
          cp xiaomi-lmi.cfg ~/.config/pmbootstrap_v3.cfg
          pmbootstrap install --password 147147
          pmbootstrap export
          cp /tmp/postmarketOS-export/boot.img out/boot-xiaomi-lmi.img
          cp /tmp/postmarketOS-export/xiaomi-lmi.img out/rootfs-xiaomi-lmi.img

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: xiaomi-lmi
          path: out/*-lmi.img*
          retention-days: 14
